name = "Error190Beta"
uuid = "11068262-b291-4362-a2ee-14c1a3606e9e"
authors = ["Jürgen Fuhrmann <juergen-fuhrmann@web.de>"]
version = "0.1.0"

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
